### ISSUE TITLE
RetroNeon not downloadable from ThemeMaster app

### ISSUE THREAD

**Issue by Akira-N28** [Jetup13/Emulationstation-OGA-Theme-Gallery#10]
Tried downloading RetroNeon directly on device using ThemeMaster but it didn't work. Other themes worked just fine.
Maybe is it because I updated repository name after you added to your gallery?
Could you please give it a check?

Thanks!

**Comment by Akira-N28** [comment]
Could it be because I updated repository name to "es-theme-RetroNeon"?

**Comment by Jetup13** [comment]
Try now, I've updated the link to reflect the change

**Comment by Akira-N28** [comment]
It is not showing up in ThemeMaster now, I tried both gallery and repository modes.

**Comment by Jetup13** [comment]
ThemeMaster will only show themes you don't have installed or need to update.

Try uninstalling the theme:

> ThemeMaster > Uninstall a theme > RetroNeon

Change to `Theme Gallery Mode`:

> ThemeMaster > Settings > Change App mode > Theme gallery by Jetup > Select screen size

Now locate the theme:

> ThemeMaster > Browse gallery > Chose Verified > Locate theme

**Comment by Akira-N28** [comment]
It didn't work. I tried on 2 different devices, ThemeMaster updated to last version on both, no RetroNeon theme loaded.
On the first one, RetroNeon simply doesn't show up in the list for verified 640*480 themes.
On the second one, it shows up but as I try to download I get this error message : 
![20230617_025816](https://github.com/Jetup13/Emulationstation-OGA-Theme-Gallery/assets/111049817/7be21873-5536-4ff9-976e-b6fe6b394169)

[UPDATE] Seems that ThemeMaster was not updating cached gallery data. Deleting old gallery.db and restarting TM did the trick, now it works as intended. Thanks for your support!
