### ISSUE TITLE
Add 1:1 themes

### ISSUE THREAD

**Issue by kleingeld1** [Jetup13/Emulationstation-OGA-Theme-Gallery#11]
Hi and thanks for this awesome repository. 
Any chance you‘ll start adding 1:1-compatible themes? With rhe RGB30‘s success that‘d be awesome.

**Comment by dani7959** [comment]
Replica supports 1:1.
Select it in the theme options ;-)

**Comment by Jetup13** [comment]
I would love to add an 1:1 category but I don't remember how Thememaster grabbed the README.md resolution info. Don't want to add it then messing up peoples install of Thememaster.

**Comment by JohnIrvine1433** [comment]
If you add it after the 960x544 column that shouldn't break ThemeMaster as I've already implemented a provision for it. 
I would still need to release a new version to integrate the 1:1 column but that can be done asynchronously.

**Comment by Jetup13** [comment]
Thanks, I added the column just now to the readme @JohnIrvine1433
