### ISSUE TITLE
New Themes

### ISSUE THREAD

**Issue by AeolusUX** [Jetup13/Emulationstation-OGA-Theme-Gallery#12]
Can you please add 
https://github.com/AeolusUX/es-theme-EpicAeolus
and 
https://github.com/AeolusUX/es-theme-Cyber2077

For easy install thru ThemeMaster?

**Comment by Jetup13** [comment]
Sorry. for the extremely late reply. I've added it to the list. Thanks and sorry again

**Comment by AeolusUX** [comment]
Here I am again can you also add my newest theme? :D

https://github.com/AeolusUX/Alekfull-SOLO-ArkOS

**Comment by Jetup13** [comment]
Added
