### ISSUE TITLE
Question: testing aspect ratios

### ISSUE THREAD

**Issue by dani7959** [Jetup13/Emulationstation-OGA-Theme-Gallery#13]
Any suggestions how to go about testing different aspect ratios for a theme, if only one device is available?
Like forcing a different ES resolution or HDMI output?

I don't mind if the image is stretched, I just want to check that all elements fit and have the corect relative sizes.

Cheers ;-)

**Comment by Jetup13** [comment]
I would use a PC version of Emulationstation and use the `--resolution` and `--windowed` launch commands. 

Examples:

RGB30:

`--resolution 720 720 --windowed`

RGB10 (ArkOS w/ES Header)

`--resolution 480 304 --windowed

Ect ect

Note that not all PC versions of Emulationstation are compatible with every theme or have slight differences. Keep this in mind.  Same goes with distributions that use Emulationstation. For instance font size is about `0.02` larger on ArkOS compared to others. Or TheRA & ArkOS using an header which takes up screen real estate. IIRC, Batocera, Retrobat, and Emulationstation-fcamod should be the builds you'd want to check first. Vanilla Emulationstation & ES-DE should be avoided as they use a slightly different format. 

You can also try using HDMI if the device supports it but typically devices go straight to highest 16x9 resolution it can do. No clue how to change as I don't handle OS stuff. 

Hope this helps
