### ISSUE TITLE
Add new themes?

### ISSUE THREAD

**Issue by jheronimus** [Jetup13/Emulationstation-OGA-Theme-Gallery#7]
Hi!

Found three cool themes that aren't in the gallery, thought you might want to add them:

**Arc** (the Google Drive version might be a bit more complete)

https://github.com/PaulloDEC/arc_es_theme
https://drive.google.com/drive/folders/1mdvFgkqerK388v124SDhal5_izn8h6gm

**Albedo**

https://github.com/mluizvitor/es-theme-albedo

**Elementerial**

https://github.com/mluizvitor/es-theme-elementerial

**Comment by mluizvitor** [comment]
Hi @jheronimus I'm the dev/designer of Albedo and Elementerial. I'm working to add both themes to this repository in a future Pull Request.

**Comment by Jetup13** [comment]
Sorry for the extremely late reply, I need to start checking my emails more. Added both with the help of @mluizvitor 

Thank you both!
