### ISSUE TITLE
Add new theme - RetroNeon

### ISSUE THREAD

**Issue by Akira-N28** [Jetup13/Emulationstation-OGA-Theme-Gallery#9]
Hi, I just finished working on a theme for ArkOS.
It began as a personal project but now I'd like to share my efforts =)
Would you consider adding it to your gallery?  Thanks

[RetroNeon - an ArkOS Theme](https://github.com/Akira-N28/RetroNeon-an_ArkOS_theme)

**Comment by Jetup13** [comment]
Nice theme! I've now added the theme to the list. Thank!
